### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by kjwilkers11** [EOP-OMB/ethics-portal#12]
Hi,

The repository seems to be missing a Framework directory. I get errors in Visual Studio and with the docker file within the Server directory.

Thanks

**Comment by LarryLambert** [comment]
This is a dependency:  https://github.com/EOP-OMB/mod-framework

**Comment by kjwilkers11** [comment]
Thanks. After installing the dependency and attempting to build the docker image, it indicates the following directory is missing from the framework:

_Server/Mod.Framework.Attachment_

**Comment by steve-kuennen** [comment]
You can remove that reference from the project. It is not used at this time.

**Comment by steve-kuennen** [comment]
I've made the change at the solution level, if you pull that you may have better luck.

**Comment by kjwilkers11** [comment]
Thanks, I incorporated the solution change. With some further testing, I get the following errors with docker build:

- #24 15.50 /src/Server/Mod.Ethics.Domain/Entities/Guidance.cs(1,21): error CS0234: The type or namespace name 'Attachments' does not exist in the namespace 'Mod.Framework' (are you missing an assembly reference?) [/src/Server/Mod.Ethics.Domain/Mod.Ethics.Domain.csproj]
- #24 15.50 /src/Server/Mod.Ethics.Domain/Entities/GuidanceAttachment.cs(1,21): error CS0234: The type or namespace name 'Attachments' does not exist in the namespace 'Mod.Framework' (are you missing an assembly reference?) [/src/Server/Mod.Ethics.Domain/Mod.Ethics.Domain.csproj]
- #24 15.50 /src/Server/Mod.Ethics.Domain/Entities/GuidanceAttachment.cs(10,39): error CS0246: The type or namespace name 'AttachmentBase' could not be found (are you missing a using directive or an assembly reference?) [/src/Server/Mod.Ethics.Domain/Mod.Ethics.Domain.csproj]

**Comment by steve-kuennen** [comment]
Ahh, appears the Attachments are being used in the existing Ethics code. I'll have to update the mod-framework on github to include the attachments. I'll work on that next week.

**Comment by steve-kuennen** [comment]
I updated the mod-framework project. It now contains the latest version that includes the attachments. Another change worth noting as I'm not entirely sure of the impact to ethics just yet, but I will be working on updating in the coming weeks. The mod framework now stores all audit dates (createdTime and modifiedTime) as UTC. It's up to the application using the application whether it needs these dates in a particular time zone for display purposes. Other than that, was mostly house keeping and updates that have occurred in the last year or so.
